server:
  port: 9890
spring:
  application:
    name: openapi-generator-ui
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  config:
    import: classpath:build-version.properties
custom:
  adsence:
    address: ${ADSENCE_ADDRESS:}
